language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
 - composer require satooshi/php-coveralls:dev-master --no-update --dev
 - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev --no-interaction --prefer-source

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text

after_script:
  - php vendor/bin/coveralls

notifications:
  slack: neropaco:jxHRwHv4jRizu1VLwmIjGLoK
